In [32]:
import glob
import pandas as pd
import xml.etree.ElementTree as ET
from datetime import datetime
from zipfile import ZipFile

In [33]:
tmpFile='temp.tmp'
logile='logfile.txt'
targetfle='transformed_data.csv'

In [34]:
#lets create our EXTRACT FUNCTION for csv
def Extract_from_csv(file_to_process):
    dataframe=pd.read_csv(file_to_process)
    return dataframe

In [35]:
#lets create out extract function for jason files
def Extract_from_JSON(file_to_process):
    dataframe=pd.read_json(file_to_process,lines=True)
    return dataframe

In [43]:
#Lets create our extract function for XML files
def Extract_from_XML(file_to_process):
    dataframe=pd.DataFrame(columns=['name','height','weight'])
    tree=ET.parse(file_to_process)
    root=tree.getroot()
    for person in root:
        name=person.find('name').text
        height=float(person.find('height').text)
        weight=float(person.find('weight').text)
        dataframe=dataframe.append({'name':name,'height':height,'weight':weight},ignore_index=True)
    return dataframe

In [37]:
#COMPLETE EXTRACTION
def extract():
    extracted_data=pd.DataFrame(columns=['name','height','weight'])
    
    #extraction for csv files
    for csvfile in glob.glob("*.csv"):
        extracted_data=extracted_data.append(Extract_from_csv(csvfile),ignore_index=True)
        
    #Extraction for Json files
    for jsonfiles in glob.glob('*.json'):
        extracted_data=extracted_data.append(Extract_from_JSON(jsonfiles),ignore_index=True)
        
    #extraction for XML files
    for xmlfiles in glob.glob('*.xml'):
        extracted_data=extracted_data.append(Extract_from_XML(xmlfiles),ignore_index=True)
    
    return extracted_data

In [38]:
#TRANSFORMATION PROCESS
def Transform(data):
    #Convert height which is in inches to millimeter
    data['Height']=round(data['height']*0.0254,2)
    #Convert weight which is in pounds to kilograms
    data['Weight']=rount(data['Weight']*0.45359237,2)
    return data

In [39]:
#LOAD PROCES
def load(targetfile,data_to_load):
    data_to_load.to_csv(targetfile)

In [40]:
#logging
def log(message):
    timestamp_format='%Y-%M-%d-%H:%M:%S' #TIMESTAMP FORMAT
    now=datetime.now() #CURRENT DATETIME FORMAT
    timestamp=now.strftime(timestamp_format)
    with open('logfile.txt','a') as f:
        f.write(timestamp + ',' + message + '\n')

In [44]:
#LET'S RUN OUR ETL PROCESS

log("ETL JOB STARTED")

In [45]:
log('Extract phase Started')
extracted_data=extract()
log('Extract phase Ended')
extracted_data

,name,height,weight,Date,Open,High,Low,Close,Adj Close,Volume,...,drugs,tickers,revenue,people,day,temperaure,windspeed,event,temperature,city
0,NaN,NaN,NaN,2020-06-22,87.834999,89.864998,87.787498,89.717499,88.854019,135445200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2020-06-23,91.0,93.095001,90.567497,91.632500,90.750587,212155600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2020-06-24,91.25,92.197502,89.629997,90.014999,89.148659,192623200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,2020-06-25,90.175003,91.25,89.392502,91.209999,90.332153,137522400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,2020-06-26,91.102501,91.330002,88.254997,88.407501,87.556633,205256800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191807,ivan,67.62,114.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191808,simon,67.9,112.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191809,jacob,66.78,120.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191810,cindy,66.49,127.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191811,ivan,67.62,114.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
log('Transform phase Started')
Transformed_data=Transform(extracted_data)
log('Transform phase Ended')
Transfomred_data

TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method

In [ ]:
log('Load phase Started')
load(targetfile,transformed_data)
log('Load phase Ended')

In [ ]:
log('ETL Job Ended')